# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorversion: '1'
  minorversion: '0'
  buildid: '$(Build.BuildNumber)'
  version: '$(majorversion)'+'.'+'$(minorversion)+'.'+'$(buildid)'
  

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: SendEmail@1
  inputs:
      To: 'nithyugurujala@gmail.com'
      From: 'nithyugurujala@gmail.com'
      Subject: 'Build Notification Email'
      BodyAsHtml: false
      Body: 'Build Notification Email'
      AddAttachment: false
      SmtpServer: 'smtp.gmail.com'
      SmtpPort: '465'
      SmtpUsername: 'nithyugurujala@gmail.com'
      SmtpPassword: 'Nithyusha23*$'
